# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "output/", "/home/vagrant/output", create: true
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.provision "shell", path: "provision.sh", privileged: false

  config.vm.define "ubuntu64" do |ubuntu64|
    ubuntu64.vm.box = "hashicorp/precise64"
  end

  config.vm.define "ubuntu32" do |ubuntu32|
    ubuntu32.vm.box = "hashicorp/precise32"
  end

end
